---
title: "Untitled"
output: html_document
---

```{r echo=F,eval=F}
setwd("~/Documents/Bristol/FTRAccounting/FTRAccountingStudy/analysis/")
```

# Introduction

See https://michaelleegiordano.com/r/multilevel-modeling-in-r/

# Load libraries

```{r message=F,warning=F}
library(lme4)
library(brms)
```

# Load data

```{r}
d = read.csv("../data/clean/data.csv",
             fileEncoding = "utf-8",
             encoding = 'utf-8')
```

# Run models

Linear model:

```{r}
#d = d[sample(1:nrow(d),2000),]

summary(lm(AAM ~
             pcftr +
             invpro+pd+indiv+mas+ua+lto+
             indul+ggr+SIZE+BTM+LEV+ROA+
             ISSUE+MEET+LOSS, data=d),
        family=exponential)
```

Simple mixed effects model with "primary" langauge family:

```{r}
dx = d[complete.cases(d[,c("AAM",'gvkey','fyear','indus','G1','pcftr')]),]
set.seed(9120)
dx = dx[sample(1:nrow(dx),10000),]
fit_lmer0 <- 
  lmer(log(0.0001+AAM) ~ 1 + 
        (1 | gvkey) +
        (1 | fyear) +
        (1 | indus) +
        (1 | G1), 
      data   = dx)
fit_lmer1 <- 
  lmer(log(0.0001+AAM) ~ 1 + 
        (1 | gvkey) +
        (1 | fyear) +
        (1 | indus) +
        (1 + pcftr| G1), 
      data   = dx)
fit_lmer2 <-update(fit_lmer1,~.+pcftr)
anova(fit_lmer0,fit_lmer1,fit_lmer2)

plot(predict(fit_lmer1),log(0.0001+dx$AAM))
abline(0,1,col=2)
```

Multi-membership model

```{r}

#reg AAM $vv4 $v2 yr_dum* indus_dum*, vce(cluster gvkey) 
#reg AAM pcftr invpro pd indiv mas ua lto indul ggr SIZE BTM LEV ROA ISSUE MEET LOSS

d$fyear = factor(d$fyear)
d$indus = factor(d$indus)


d = d[sample(1:nrow(d),3000),]

fit_mm <- 
  brm(AAM ~ 1 + pcftr + 
             invpro+pd+indiv+mas+ua+lto+
             indul+ggr+SIZE+BTM+LEV+ROA+
             ISSUE+MEET+LOSS+
        (1 | gvkey) +
        (1 | fyear) +
        (1 | indus) +
        (1 | mm(G1, G2, G3, # genuses
                weights = cbind(G1.p, G2.p, G3.p))), 
      data   = d,
      family = exponential,
      warmup = 0,
      iter   = 1,
      thin =   1,
      chains = 1,
      save_dso = TRUE)

save(fit_mm,file="../data/clean/brm_model_langFamRanEf.Rdat")

```

